In [ ]:
"""
Linear Regression, Logistic Regression, KNN, K-Means, PCA, Decision Trees / Random Forests, Naive Bayes, 
Neural Network, Ridge Regression
"""

In [ ]:
import numpy as np

In [181]:
import pandas as pd
file = "/Users/jeremynixon/Dropbox/python/Ultimate Frisbee/Indoor.csv"
dataset = pd.read_csv(file)
x_train = dataset['Goals']
x_train = np.column_stack((np.ones(len(x_train)), x_train))
y_train = np.array(dataset['Assists'])

In [182]:
# Linear Regression

def linear_regression(x, y, lr=.0001, ep = .0000001, num_iter = 100000):
    rows, cols = x.shape
    betas = np.zeros(cols)
    betas = betas + lr * sum([(y[i] - np.dot(x[i], betas)) * x[i] for i in range(rows)])
    sse = sum([(y[i] - np.dot(x[i], betas))**2 for i in range(rows)])
    for i in xrange(num_iter):
        betas = betas + lr * sum([(y[i] - np.dot(x[i], betas)) * x[i] for i in range(rows)])
        e = sum([(y[i] - np.dot(x[i], betas))**2 for i in range(rows)])
        if abs(e - sse) <= ep:
            return betas
        sse = e
    return 'Failed to Converge'

In [183]:
linear_regression(x_train, y_train)

array([ 1.40663308,  0.74461107])

In [179]:
def lr_thetas(x, y, lr = .0001, ep = .00001, num_iter = 100000):
    rows, cols = x.shape
    thetas = np.zeros(cols)
    thetas = thetas + lr * sum([(y[i] - np.dot(thetas, x[i])) * x[i] for i in xrange(rows)])
    sse = sum([(y[i] - np.dot(x[i], thetas))**2 for i in xrange(rows)])
    for i in xrange(num_iter):
        thetas = thetas + lr * sum([(y[i] - np.dot(thetas, x[i])) * x[i] for i in xrange(rows)])
        e = sum([(y[i] - np.dot(x[i], thetas))**2 for i in xrange(rows)])
        if abs(e-sse) < ep:
            return thetas
        sse = e
    return 'Did Not Converge'

In [180]:
lr_thetas(x_train, y_train)

array([ 1.40306998,  0.74491024])

In [175]:
def lr(x, y):
    xt = x.T
    xtx = np.dot(xt, x)
    inv = np.linalg.inv(xtx)
    weights = np.dot(inv, np.dot(xt, y))
    return weights

In [176]:
lr(x_train, y_train)

array([ 1.407029  ,  0.74457783])

In [56]:
import pandas as pd
import sklearn.cross_validation

iris = pd.read_csv('/Users/jeremynixon/Dropbox/python/Oracle Development/iris.data', header=None)
iris = iris[:100]
y = np.array(iris[4])
new_y = []
for i in y:
    if i == 'Iris-setosa':
        new_y.append(1)
    elif i == 'Iris-versicolor':
        new_y.append(0)
y = np.array(new_y)
x = np.array(iris.drop([4], 1))
x = np.hstack((np.ones((x.shape[0],1)),x))
x_train, x_test, y_train, y_test = sklearn.cross_validation.train_test_split(x, y, test_size = .20, random_state=42)

In [66]:
from math import e
def h(x, thetas):
    return e**(np.dot(x, thetas))/(1.0 + e**np.dot(x, thetas))

def logistic_regression(x, y, lr = .001, num_iters = 1000):
    rows, cols = x.shape
    thetas = np.ones(cols)
    indices = np.arange(rows)
    for iteration in xrange(num_iters):
        permutation = np.random.permutation(indices)
        for i in permutation:
            thetas = thetas + lr * (y[i] - h(x[i], thetas)) * x[i]
    return thetas

In [71]:
thetas = logistic_regression(x_train, y_train)
for i, v in enumerate(x_test):
    n = np.dot(thetas, v)
    if n > 0:
        n = 1
    else:
        n = 0
    print [n, y_test[i]],

[0, 0] [0, 0] [0, 0] [1, 1] [1, 1] [1, 1] [1, 1] [0, 0] [1, 1] [1, 1] [1, 1] [1, 1] [0, 0] [1, 1] [0, 0] [1, 1] [0, 0] [0, 0] [1, 1] [1, 1]


In [89]:
print x_train[1]
print x_train[2]
print ed(x_train[1], x_train[2])
print ed(x_train[1], x_train[1])
print eucledian_distance(x_train[1], x_train[2])
print eucledian_distance(x_train[1], x_train[1])


[ 1.   5.6  3.   4.1  1.3]
[ 1.   5.   3.4  1.6  0.4]
7.58
0.0
7.58
0.0


In [111]:
def eucledian_distance(vector1, vector2):
    return sum([(i**2) for i in vector1-vector2])

def get_neighbors(x, point, k):
    d = []
    for i, v in enumerate(x):
        d.append([i, eucledian_distance(v, point)])
    d.sort(key = lambda t:t[1])
    
    n = []
    for i in xrange(k):
        n.append(d[i][0])
    return n

def get_outcome(n, y):
    ht = {}
    for i in n:
        try:
            ht[y[i]] += 1
        except KeyError:
            ht[y[i]] = 1
    
    maximus = 0
    for i, v in ht.iteritems():
        if v > maximus:
            maximus = v
            max_index = i
    
    return max_index
    
        
def KNN(x_train, y_train, x_test, k):
    predictions = []
    for i in x_test:
        neighbors = get_neighbors(x_train, i, k)
        predictions.append(get_outcome(neighbors, y_train))
    return predictions

In [114]:
print KNN(x_train, y_train, x_test, 4)
print y_test

[0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1]
[0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1]


In [140]:
file = "/Users/jeremynixon/Dropbox/python/Ultimate Frisbee/Indoor.csv"
dataset = pd.read_csv(file)
for_cluster = dataset[['Games','Goals','Assists','Ds','Turns','Drops']]
for_cluster = np.array(for_cluster)

In [137]:
import random
import numpy as np

# May not assign a datapoint to every cluster, and so can lose clusters
# Convergence check is buggy, will return true if it finds the first one to be correct

def ed(v1, v2):
    return sum([(i**2) for i in v1-v2])

def get_clusters(x, means):
    clusters = {}
    for point in x:
        minimum = float('inf')
        for i, v in enumerate(means):
            d = ed(v, point)
            if d < minimum:
                min_index = i
                minimum = d
        try:
            clusters[min_index].append(point)
        except KeyError:
            clusters[min_index] = [point]
            
    return clusters

def get_means(x, clusters):
    means = []
    for i, v in clusters.iteritems():
        means.append(np.mean(v))
    return means
        

def converged(means, oldmeans):
    for i in means:
        for j in oldmeans:
            if (i == j).all():
                return True
            else:
                return False
#    return set([tuple(a) for a in means]) == set([tuple(a) for a in oldmeans])
            

def k_means(x, k):
    means = random.sample(x, k)
    oldmeans = random.sample(x, k)
    while(not converged(means, oldmeans)):
        oldmeans = means
        clusters = get_clusters(x, means)
        means = get_means(x, clusters)
    return clusters

In [141]:
k_means(for_cluster, 4)

{0: [array([ 6, 15, 16,  7, 12,  2]),
  array([ 5, 14, 13,  7, 11,  0]),
  array([ 6,  8, 15,  3, 10,  0]),
  array([ 7, 11, 14,  8, 11,  0]),
  array([ 7, 23,  5,  6,  5,  0]),
  array([ 8, 18,  4,  5,  5,  4]),
  array([ 7, 16, 15,  4, 16,  0]),
  array([ 8, 19,  3,  1, 13,  5]),
  array([ 8, 10,  7,  6,  6,  1]),
  array([ 7, 13, 13,  6, 14,  2]),
  array([ 5, 27, 13, 11,  4,  2]),
  array([ 6, 12, 17, 11,  7,  3]),
  array([ 6, 12,  7,  6,  8,  3]),
  array([ 4,  8, 14,  5,  8,  2]),
  array([ 6, 13,  0,  6, 12,  4]),
  array([ 6, 18, 10,  8,  5,  1]),
  array([ 5,  7, 15,  3, 11,  2]),
  array([ 6,  7, 10,  0, 18,  1])],
 1: [array([ 4, 13,  4,  7,  6,  3]),
  array([ 5,  8, 12,  4,  5,  1]),
  array([ 6, 10,  0,  4,  5,  1]),
  array([ 5,  2,  4,  1, 11,  2]),
  array([4, 7, 4, 2, 6, 2]),
  array([4, 8, 5, 2, 9, 6]),
  array([ 3,  1, 12,  5, 11,  2]),
  array([5, 7, 4, 3, 7, 2]),
  array([ 5, 11,  1,  2,  2,  2]),
  array([7, 4, 4, 6, 6, 1]),
  array([ 5, 10,  4,  1,  4,  1]),
  

In [142]:
def PCA(x):
    M = (x - np.mean(x.T, axis=1)).T
    cov = np.cov(M) # Covariance Matrix
    lv, coef = np.linalg.eig(cov) # Latent Variables, Coefficients
    proj = np.dot(coef.T, M)
    return coef, proj, lv

In [143]:
PCA(for_cluster)

(array([[ 0.18553772,  0.14628245,  0.19947737, -0.58959991,  0.7452515 ,
          0.03685275],
        [ 0.47287921,  0.79966225,  0.06194678,  0.06547875, -0.22566889,
         -0.27905953],
        [ 0.68175687, -0.40519258, -0.57387528, -0.00202164,  0.07127181,
         -0.19133728],
        [ 0.24870082,  0.17087247, -0.14550326,  0.05753527, -0.05741096,
          0.93870814],
        [ 0.45984355, -0.37912233,  0.76939554,  0.03403977, -0.22158788,
          0.0508013 ],
        [ 0.06213208,  0.04505072,  0.1178891 ,  0.80225394,  0.57982486,
         -0.02009844]]),
 array([[  1.59075623e+01,   3.51509377e+01,   2.32228118e+01,
           3.71271687e+00,   5.65770330e+00,  -8.37933853e+00,
          -1.39208296e+00,  -7.92090152e+00,  -9.02575082e+00,
          -9.59751323e+00,  -6.79252596e+00,  -1.05902545e+01,
          -1.01560159e+01,  -5.58535970e-01,   1.26197671e+01,
          -8.95001837e+00,  -4.30194571e-01,   2.35250049e+00,
          -8.80327279e+00,   9.8768964

In [144]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';')
Y = df['quality'].values
df = df.drop('quality',1)
x_train, x_test, y_train, y_test = sklearn.cross_validation.train_test_split(df, Y, test_size = .20, random_state=42)

In [162]:
# Random Forest

import math
import random
import pandas as pd
import numpy as np
import sklearn.cross_validation

class Tree():
    def __init__(self, parents = None):
        self.parents = parents
        self.children = []
        self.split_feature = None
        self.split_feature_value = None
        self.label = None
        

def entropy(y):
    distribution = [(list(y).count(i)/float(len(y))) for i in set(y)]
    return -sum([p * math.log(p,2) for p in distribution])

def split_data(x, y, feature_index):
    for a in set(x[:, feature_index]):
        data_subset = []
        for i, point in enumerate(x):
            if point[feature_index] == a:
                data_subset.append([point, y[i]])
        yield data_subset
        
def gain(x, y, feature_


In [163]:
for i in split_data(x, y, 2):
    print i

[[array([ 1. ,  5.1,  3.5,  1.4,  0.2]), 1], [array([ 1. ,  5.1,  3.5,  1.4,  0.3]), 1], [array([ 1. ,  5.2,  3.5,  1.5,  0.2]), 1], [array([ 1. ,  5.5,  3.5,  1.3,  0.2]), 1], [array([ 1. ,  5. ,  3.5,  1.3,  0.3]), 1], [array([ 1. ,  5. ,  3.5,  1.6,  0.6]), 1]]
[[array([ 1. ,  4.6,  3.1,  1.5,  0.2]), 1], [array([ 1. ,  4.9,  3.1,  1.5,  0.1]), 1], [array([ 1. ,  4.8,  3.1,  1.6,  0.2]), 1], [array([ 1. ,  4.9,  3.1,  1.5,  0.1]), 1], [array([ 1. ,  4.9,  3.1,  1.5,  0.1]), 1], [array([ 1. ,  6.9,  3.1,  4.9,  1.5]), 0], [array([ 1. ,  6.7,  3.1,  4.4,  1.4]), 0], [array([ 1. ,  6.7,  3.1,  4.7,  1.5]), 0]]
[[array([ 1. ,  5. ,  2. ,  3.5,  1. ]), 0]]
[[array([ 1. ,  4.9,  3. ,  1.4,  0.2]), 1], [array([ 1. ,  4.8,  3. ,  1.4,  0.1]), 1], [array([ 1. ,  4.3,  3. ,  1.1,  0.1]), 1], [array([ 1. ,  5. ,  3. ,  1.6,  0.2]), 1], [array([ 1. ,  4.4,  3. ,  1.3,  0.2]), 1], [array([ 1. ,  4.8,  3. ,  1.4,  0.3]), 1], [array([ 1. ,  5.9,  3. ,  4.2,  1.5]), 0], [array([ 1. ,  5.6,  3. ,  4

In [157]:
x

array([[ 1. ,  5.1,  3.5,  1.4,  0.2],
       [ 1. ,  4.9,  3. ,  1.4,  0.2],
       [ 1. ,  4.7,  3.2,  1.3,  0.2],
       [ 1. ,  4.6,  3.1,  1.5,  0.2],
       [ 1. ,  5. ,  3.6,  1.4,  0.2],
       [ 1. ,  5.4,  3.9,  1.7,  0.4],
       [ 1. ,  4.6,  3.4,  1.4,  0.3],
       [ 1. ,  5. ,  3.4,  1.5,  0.2],
       [ 1. ,  4.4,  2.9,  1.4,  0.2],
       [ 1. ,  4.9,  3.1,  1.5,  0.1],
       [ 1. ,  5.4,  3.7,  1.5,  0.2],
       [ 1. ,  4.8,  3.4,  1.6,  0.2],
       [ 1. ,  4.8,  3. ,  1.4,  0.1],
       [ 1. ,  4.3,  3. ,  1.1,  0.1],
       [ 1. ,  5.8,  4. ,  1.2,  0.2],
       [ 1. ,  5.7,  4.4,  1.5,  0.4],
       [ 1. ,  5.4,  3.9,  1.3,  0.4],
       [ 1. ,  5.1,  3.5,  1.4,  0.3],
       [ 1. ,  5.7,  3.8,  1.7,  0.3],
       [ 1. ,  5.1,  3.8,  1.5,  0.3],
       [ 1. ,  5.4,  3.4,  1.7,  0.2],
       [ 1. ,  5.1,  3.7,  1.5,  0.4],
       [ 1. ,  4.6,  3.6,  1. ,  0.2],
       [ 1. ,  5.1,  3.3,  1.7,  0.5],
       [ 1. ,  4.8,  3.4,  1.9,  0.2],
       [ 1. ,  5. ,  3. ,